@startuml
!include ../src/Rendering.puml
''----------------------------------------------------------------------------------------------------------------------
'' Tests
''----------------------------------------------------------------------------------------------------------------------
!procedure hide_description_should_set_show_desc_to_false()
    '' Arrange: зарегистрировать дескриптор и декоратор через Common
    ''   $register_descriptor("HD", {"type":"Test","label":"Test"})
    ''   $register_decorator("HD", {"is_extern":%false(),"show_desc":%true(),"styles":[]})
    '' Act: HideDescription(HD); $decorator = $get_decorator("HD")
    '' Assert: $decorator.show_desc == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure apply_style_should_add_to_styles_array()
    '' Arrange: зарегистрировать дескриптор и декоратор через Common
    ''   $register_descriptor("AS", {"type":"Test","label":"Test"})
    ''   $register_decorator("AS", {"is_extern":%false(),"show_desc":%true(),"styles":[]})
    '' Act: ApplyStyle(AS, "bright_and_bold"); $decorator = $get_decorator("AS")
    '' Assert: %size($decorator.styles) == 1; $decorator.styles[0] == "bright_and_bold"
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure apply_style_should_not_duplicate()
    '' Arrange: зарегистрировать декоратор со стилем
    ''   $register_descriptor("DUP", {"type":"Test","label":"Test"})
    ''   $register_decorator("DUP", {"is_extern":%false(),"show_desc":%true(),"styles":["bold"]})
    '' Act: ApplyStyle(DUP, "bold"); $decorator = $get_decorator("DUP")
    '' Assert: %size($decorator.styles) == 1 (стиль "bold" уже был, дубликат не добавлен)
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideLabel
''----------------------------------------------------------------------------------------------------------------------
!procedure hidelabel_should_set_show_label_false()
    '' Arrange: $register_decorator("RL", {"show_label":%true(),"show_techn":%true(),"show_descr":%true(),"link":"","sprite":"","styles":[]})
    '' Act: HideLabel(RL); $decorator = $get_decorator("RL")
    '' Assert: $decorator.show_label == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideTechnology
''----------------------------------------------------------------------------------------------------------------------
!procedure hidetechnology_should_set_show_techn_false()
    '' Arrange: $register_decorator("RT", {"show_label":%true(),"show_techn":%true(),"show_descr":%true(),"link":"","sprite":"","styles":[]})
    '' Act: HideTechnology(RT); $decorator = $get_decorator("RT")
    '' Assert: $decorator.show_techn == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideDescription on relations
''----------------------------------------------------------------------------------------------------------------------
!procedure hidedescription_should_hide_descr_for_relation()
    '' Arrange: $register_decorator("RD", {"show_label":%true(),"show_techn":%true(),"show_descr":%true(),"link":"","sprite":"","styles":[]})
    '' Act: HideDescription(RD); $decorator = $get_decorator("RD")
    '' Assert: $decorator.show_descr == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests RUN!
''----------------------------------------------------------------------------------------------------------------------
hide_description_should_set_show_desc_to_false()
apply_style_should_add_to_styles_array()
apply_style_should_not_duplicate()
hidelabel_should_set_show_label_false()
hidetechnology_should_set_show_techn_false()
hidedescription_should_hide_descr_for_relation()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml
