@startuml
!include ../src/Rendering.puml
''----------------------------------------------------------------------------------------------------------------------
'' Tests
''----------------------------------------------------------------------------------------------------------------------
!procedure hide_description_should_set_show_desc_to_false()
    '' Arrange
    !$desc = {}
    !$desc = $json_add($desc, "type", "Test")
    !$desc = $json_add($desc, "label", "Test")
    $register_descriptor("HD", $desc)
    !$decor = {}
    !$decor = $json_add($decor, "is_extern", %false())
    !$decor = $json_add($decor, "show_desc", %true())
    !$decor = $json_add($decor, "styles", [])
    $register_decorator("HD", $decor)

    '' Act
    HideDescription(HD)
    !$decorator = $get_decorator("HD")

    '' Assert
    !assert $decorator.show_desc == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure apply_style_should_add_to_styles_array()
    '' Arrange
    !$desc = {}
    !$desc = $json_add($desc, "type", "Test")
    !$desc = $json_add($desc, "label", "Test")
    $register_descriptor("AS", $desc)
    !$decor = {}
    !$decor = $json_add($decor, "is_extern", %false())
    !$decor = $json_add($decor, "show_desc", %true())
    !$decor = $json_add($decor, "styles", [])
    $register_decorator("AS", $decor)

    '' Act
    ApplyStyle(AS, "bright_and_bold")
    !$decorator = $get_decorator("AS")

    '' Assert
    !assert %size($decorator.styles) == 1
    !assert $decorator.styles[0] == "bright_and_bold"
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure apply_style_should_not_duplicate()
    '' Arrange
    !$desc = {}
    !$desc = $json_add($desc, "type", "Test")
    !$desc = $json_add($desc, "label", "Test")
    $register_descriptor("DUP", $desc)
    !$decor = {}
    !$decor = $json_add($decor, "is_extern", %false())
    !$decor = $json_add($decor, "show_desc", %true())
    !$decor = $json_add($decor, "styles", ["bold"])
    $register_decorator("DUP", $decor)

    '' Act
    ApplyStyle(DUP, "bold")
    !$decorator = $get_decorator("DUP")

    '' Assert
    !assert %size($decorator.styles) == 1
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideLabel
''----------------------------------------------------------------------------------------------------------------------
!procedure hidelabel_should_set_show_label_false()
    '' Arrange
    !$decor = {}
    !$decor = $json_add($decor, "show_label", %true())
    !$decor = $json_add($decor, "show_techn", %true())
    !$decor = $json_add($decor, "show_descr", %true())
    !$decor = $json_add($decor, "link", "")
    !$decor = $json_add($decor, "sprite", "")
    !$decor = $json_add($decor, "styles", [])
    $register_decorator("RL", $decor)

    '' Act
    HideLabel(RL)
    !$decorator = $get_decorator("RL")

    '' Assert
    !assert $decorator.show_label == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideTechnology
''----------------------------------------------------------------------------------------------------------------------
!procedure hidetechnology_should_set_show_techn_false()
    '' Arrange
    !$decor = {}
    !$decor = $json_add($decor, "show_label", %true())
    !$decor = $json_add($decor, "show_techn", %true())
    !$decor = $json_add($decor, "show_descr", %true())
    !$decor = $json_add($decor, "link", "")
    !$decor = $json_add($decor, "sprite", "")
    !$decor = $json_add($decor, "styles", [])
    $register_decorator("RT", $decor)

    '' Act
    HideTechnology(RT)
    !$decorator = $get_decorator("RT")

    '' Assert
    !assert $decorator.show_techn == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests for HideDescription on relations
''----------------------------------------------------------------------------------------------------------------------
!procedure hidedescription_should_hide_descr_for_relation()
    '' Arrange
    !$decor = {}
    !$decor = $json_add($decor, "show_label", %true())
    !$decor = $json_add($decor, "show_techn", %true())
    !$decor = $json_add($decor, "show_descr", %true())
    !$decor = $json_add($decor, "link", "")
    !$decor = $json_add($decor, "sprite", "")
    !$decor = $json_add($decor, "styles", [])
    $register_decorator("RD", $decor)

    '' Act
    HideDescription(RD)
    !$decorator = $get_decorator("RD")

    '' Assert
    !assert $decorator.show_descr == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests RUN!
''----------------------------------------------------------------------------------------------------------------------
hide_description_should_set_show_desc_to_false()
apply_style_should_add_to_styles_array()
apply_style_should_not_duplicate()
hidelabel_should_set_show_label_false()
hidetechnology_should_set_show_techn_false()
hidedescription_should_hide_descr_for_relation()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml
