@startuml
!include ../src/Utils.puml
''----------------------------------------------------------------------------------------------------------------------
'' Tests
''----------------------------------------------------------------------------------------------------------------------
!procedure get_library_version_returns_semantic_version_number()
    '' Arrange, Act
    !$actual = $get_library_version()

    '' Assert
    !$pattern = "/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm"
    !assert %size(%splitstr_regex($actual, $pattern)) == 1
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure format_should_create_a_string_from_pattern_and_positional_arguments()
    '' Arrange, Act
    !$actual = $format("This is %1 with arguments %2 and %3.", "expression", "x", "y")

    '' Assert
    !assert "This is expression with arguments x and y." == $actual
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure contain_in_list_should_find_existing_item()
    '' Arrange
    !$collection = [1, 2, 3]

    '' Act
    !$exists = $contain_in_list($collection, 2)

    '' Assert
    !assert $exists == %true()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure contain_in_list_should_not_find_missing_item()
    '' Arrange
    !$collection = [1, 2, 3]

    '' Act
    !$exists = $contain_in_list($collection, 4)

    '' Assert
    !assert $exists == %false()
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure append_to_list_should_add_item_to_end()
    '' Arrange
    !$collection = [1, 2]

    '' Act
    !$actual = $append_to_list($collection, 3)

    '' Assert
    !assert %size($actual) == 3
    !assert $actual[2] == 3
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure append_to_list_should_add_string_to_end()
    '' Arrange
    !$collection = ["X", "Y"]

    '' Act
    !$actual = $append_to_list($collection, "Z")

    '' Assert
    !assert %size($actual) == 3
    !assert $actual[2] == "Z"
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure append_to_list_should_add_to_empty_collection()
    '' Arrange
    !$collection = []

    '' Act
    !$actual = $append_to_list($collection, 1)

    '' Assert
    !assert %size($actual) == 1
    !assert $actual[0] == 1
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure json_add_append_key_and_value_to_json_object()
    '' Arrange
    !$json = {}

    '' Act
    !$json = $json_add($json, "Y", 20)

    '' Assert
    !assert $json.Y == 20
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
!procedure json_add_append_nested_json_to_json_object()
    '' Arrange
    !$json = { "City": "Moscow" }
    !$value = { "Alt": 10, "Lon": 20 }

    '' Act
    !$json = $json_add($json, "Pos", $value)

    '' Assert
    !assert $json.City == "Moscow"
    !assert $json.Pos.Alt == 10
    !assert $json.Pos.Lon == 20
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests RUN!
''----------------------------------------------------------------------------------------------------------------------
get_library_version_returns_semantic_version_number()
format_should_create_a_string_from_pattern_and_positional_arguments()
contain_in_list_should_find_existing_item()
contain_in_list_should_not_find_missing_item()
append_to_list_should_add_item_to_end()
append_to_list_should_add_string_to_end()
append_to_list_should_add_to_empty_collection()
json_add_append_key_and_value_to_json_object()
json_add_append_nested_json_to_json_object()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml