@startuml
!include ../src/Utils.puml
''----------------------------------------------------------------------------------------------------------------------
'' Tests
''----------------------------------------------------------------------------------------------------------------------
!procedure get_library_version_returns_semantic_version_number()
    '' Arrange, Act
    !$actual = $get_library_version()

    '' Assert
    !$pattern = "/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm"
    !assert %size(%splitstr_regex($actual, $pattern)) == 1

!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Tests RUN!
''----------------------------------------------------------------------------------------------------------------------
get_library_version_returns_semantic_version_number()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml