@startuml
!include ../../../src/C4/Context.puml

\ Регистрация элемента
$ContainerQueue(PaymentsQueue, "Очередь событий", "RabbitMQ 3.12", \r
                "Асинхронные уведомления", $boundary=CoreSystem)
@enduml
