@startuml
''----------------------------------------------------------------------------------------------------------------------
'' Get PlantUml DSL library version.
'' example: !$ver = $get_library_version()
!function $get_library_version()
    !if %file_exists("../version.json")
        !$ver = %load_json("../version.json")
    !else if %file_exists("version.json")
        !$ver = %load_json("version.json")
    !endif
    !return $ver.version
!endfunction
''----------------------------------------------------------------------------------------------------------------------
!procedure $trace($message, $source=%filename())
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Force the script execution abort with error.
'' args: $message - error message to display
''       $source - source file name (defaults to %filename())
'' example: $fail("Something went wrong")
!procedure $fail($message, $source=%filename())
    !assert %false() : 'FAIL: "' + $message + '" in "' + $source + '"'
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
@enduml