@startuml
''----------------------------------------------------------------------------------------------------------------------
'' Sprite-обёртка database.
'' Тонкая обёртка над пиктограммой database.
'' Саму пиктограмму регистрирует пользователь через !include <material/database> в самом
'' верху своей диаграммы.
'' Обёртка предоставляет функцию $getDatabase($alias), чтобы имя спрайта было стабильным
'' вне зависимости от пути include.
''----------------------------------------------------------------------------------------------------------------------
!unquoted function $getDatabase($alias)
  !if %substr($alias, 0, 1) == "&" || %substr($alias, 0, 4) == "img:"
    !return "<" + $alias + ">"
  !else
    !return "<$" + $alias + ">"
  !endif
!endfunction
@enduml