@startuml
''----------------------------------------------------------------------------------------------------------------------
'' Sprite-обёртка server.
'' Тонкая обёртка над пиктограммой server.
'' Саму пиктограмму регистрирует пользователь через !include <tupadr3/font-awesome/server> в самом
'' верху своей диаграммы.
'' Обёртка предоставляет функцию $getServer($alias), чтобы имя спрайта было стабильным.
''----------------------------------------------------------------------------------------------------------------------
!unquoted function $getServer($alias)
  !if %substr($alias, 0, 1) == "&" || %substr($alias, 0, 4) == "img:"
    !return "<" + $alias + ">"
  !else
    !return "<$" + $alias + ">"
  !endif
!endfunction
@enduml