@startuml
!include ../../src/C4/Context.puml

<style>
.firewall {
  LineColor: red;
  FontColor: darkred
}
</style>
HIDE_STEREOTYPE()
''-----------------------------------------------------------------------
'' Включение элементов в диаграмму
''-----------------------------------------------------------------------
Persons("Elements", User)
Persons_Ext("Elements", Admin)

''-----------------------------------------------------------------------
'' Включение связей в диаграмму
''-----------------------------------------------------------------------
Relations("Relations", User-Admin)

''-----------------------------------------------------------------------
'' Настройка опций отображения
''-----------------------------------------------------------------------
HideDescription(User-Admin)
ApplyStyle(User-Admin, "firewall")
ApplySprite(User-Admin, "&key")

''-----------------------------------------------------------------------
'' Настройка диаграммы и рендеринг
''-----------------------------------------------------------------------
Diagram($title="System Context diagram", ...)

@enduml
