@startuml
!include ../../src/Utils.puml
'' !include ../../src/C4/Context.puml

''-----------------------------------------------------------------------
'' Включение элементов в диаграмму
''-----------------------------------------------------------------------
Persons(User)
Systems(ERP)
Systems_Ext(1C, SSO)

''-----------------------------------------------------------------------
'' Включение связей в диаграмму
''-----------------------------------------------------------------------
Relations(User-ERP, ERP-1C, ERP-SSO)

''-----------------------------------------------------------------------
'' Относительные выравнивания
''-----------------------------------------------------------------------
Align_Down(User-ERP, ERP-1C)
Align_Right(ERP-SSO)

''-----------------------------------------------------------------------
'' Дополнения диаграммы
''-----------------------------------------------------------------------
Note_Down(SSO, "Это может быть Keycloak")

''-----------------------------------------------------------------------
'' Настройка рендеринга
''-----------------------------------------------------------------------
Diagram($title="System Context diagram", ...)

@enduml