@startuml
!include ../../src/C4/Context.puml
''-----------------------------------------------------------------------
'' Включение элементов в диаграмму
''-----------------------------------------------------------------------
Persons("Elements", User)
Persons_Ext("Elements", Admin)

''-----------------------------------------------------------------------
'' Дополнения диаграммы
''-----------------------------------------------------------------------
HideDescription(Admin)

''-----------------------------------------------------------------------
'' Настройка диаграммы и рендеринг
''-----------------------------------------------------------------------
Diagram($title="C4 System Context - Persons", ...)

@enduml