@startuml
!include ../../src/C4/Context.puml
<style>
    .alert {
      FontColor: red;
    }
  }
</style>

''-----------------------------------------------------------------------
'' Включение элементов в диаграмму
''-----------------------------------------------------------------------
Persons("Elements", User)
Persons_Ext("Elements", Admin)
''-----------------------------------------------------------------------
'' Дополнения диаграммы
''-----------------------------------------------------------------------
HideDescription(Admin)
ApplyStyle(Admin, "alert")
''-----------------------------------------------------------------------
'' Настройка диаграммы и рендеринг
''-----------------------------------------------------------------------
Diagram($title="C4 System Context - Persons", ...)

@enduml