@startuml
!include ../../src/C4/Context.puml

''-----------------------------------------------------------------------
'' Включение элементов в диаграмму
''-----------------------------------------------------------------------
Persons("Elements", User)

''-----------------------------------------------------------------------
'' Дополнения диаграммы
''-----------------------------------------------------------------------
HideDescription(User)

''-----------------------------------------------------------------------
'' Настройка диаграммы и рендеринг
''-----------------------------------------------------------------------
Diagram($title="C4 System Context - Persons", ...)

@enduml